services:
  client:
    build:
      context: ./client
      target: client-dev
    volumes:
      - ./client/src/:/usr/local/app/src/
    ports:
      - 127.0.0.1:5173:5173
    env_file:
      - ./client/.env.docker
  backend:
    build:
      context: ./server
      target: backend-dev
    volumes:
        - ./server/src/:/usr/local/app/src/
    env_file:
      - ./server/.env.docker
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16.9
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./server/.env.db
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 4s
      timeout: 2s
      retries: 5
      
volumes:
  postgres_data:
