[project]
name = "raviolichess"
description = "chess server application"
readme = "README.md"
version = "0.1.0"
requires-python = ">=3.13"
[dependency-groups]
dev = ["honcho>=2.0.0", "ruff>=0.14.10"]
[tool.uv.workspace]
members = ["backend/*"]
exclude = ["backend/scripts", "backend/playground"]

[tool.uv.sources]
ravioli-core = { workspace = true }
