# Generated by Django 5.2.4 on 2025-09-17 19:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_friendlist_friends_alter_friendlist_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendList',
            new_name='Friends',
        ),
        migrations.RenameField(
            model_name='friends',
            old_name='friends',
            new_name='friendlist',
        ),
    ]
