# Generated by Django 5.2.4 on 2025-10-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_alter_preference_pieces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='board',
            field=models.CharField(choices=[('wood', 'Wood'), ('blue', 'Blue'), ('blue2', 'Blue2'), ('brown', 'Brown')], default='wood', max_length=15),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pieces',
            field=models.CharField(choices=[('base', 'Base'), ('wiki', 'Wiki')], default='base', max_length=15),
        ),
    ]
