# Generated by Django 5.2.4 on 2025-10-21 23:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0005_alter_preference_board_alter_preference_pieces"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Preference",
            new_name="Profile",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="pieces",
            new_name="pieceset",
        ),
    ]
