[project]
name = "ravioli-service"
version = "0.1.0"
description = "db communication settings"
authors = [
    { name = "Victor", email = "victorlecouteur@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.31.0",
    "msgspec>=0.20.0",
    "orjson>=3.11.7",
    "pydantic-settings>=2.12.0",
    "redis[hiredis]>=7.4.0",
    "sqlalchemy[asyncio]>=2.0.45",
]
[tool.ruff]
extend = "../ruff.toml"
extend-exclude = ["alembic"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

