"""create chess position table

Revision ID: 5207e94f04bd
Revises: 3f5e3cc97c6d
Create Date: 2026-03-05 16:40:45.842337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5207e94f04bd'
down_revision: Union[str, Sequence[str], None] = '3f5e3cc97c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chess_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eco', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fen', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chess_position')),
    sa.UniqueConstraint('eco', name=op.f('uq_chess_position_eco'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chess_position')
    # ### end Alembic commands ###
