[project]
name = "ravioli-core"
version = "0.1.0"
description = "utilities and shared services"
authors = [
    { name = "Victor", email = "victorlecouteur@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "cachelib>=0.13.0",
    "jinja2>=3.1.6",
    "msgspec>=0.20.0",
    "orjson>=3.11.7",
    "pydantic-settings>=2.14.2",
    "redis[hiredis]==7.4.0",
    "sqlalchemy[asyncio]>=2.0.45",
]
[tool.ruff]
extend = "../ruff.toml"
extend-exclude = ["alembic"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["ravioli_core"]
