# Generated by Django 5.2.4 on 2025-10-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0003_alter_preference_board"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="pieces",
            field=models.CharField(default="base", max_length=15),
        ),
    ]
