from collections.abc import AsyncGenerator
from typing import Any, Protocol, overload


class ChannelBackend(Protocol):
    async def publish(self, channel: str, message: bytes) -> None: ...
    async def subscribe(self, *args, **kwargs) -> None: ...
    async def unsubscribe(self, *args, **kwargs) -> None: ...
    async def stream(self) -> AsyncGenerator[tuple[str, bytes]]: ...
    async def stop(self) -> None: ...


class Subscriber(Protocol):
    def put_nowait(self, item: Any) -> bool: ...
    @overload
    async def iter_message(self) -> AsyncGenerator: ...
    async def iter_message[T](self, type_arg: type[T]) -> AsyncGenerator[T]: ...
    def shutdown(self, immediate=False) -> None: ...
