# Generated by Django 5.2.4 on 2025-07-22 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'get_latest_by': 'pub_date', 'ordering': ['pub_date']},
        ),
    ]
