# Generated by Django 5.2.4 on 2025-07-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CANCELED', 'Cancelled'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending')], max_length=24),
        ),
    ]
