[project]
name = "ravioli-fastapi"
version = "0.1.0"
description = "HTTP and Websocket server"
requires-python = ">=3.13"
dependencies = [
    "ravioli-core",
    "email-validator>=2.3.0",
    "fastapi-pagination>=0.15.12",
    "fastapi[standard-no-fastapi-cloud-cli]>=0.128.5",
    "itsdangerous>=2.2.0",
    "pwdlib[argon2]>=0.3.0",
    "uvicorn[standard]>=0.38.0",
]

[tool.ruff]
extend = "../ruff.toml"