"""create game table

Revision ID: a43f37c0e5c1
Revises: 5207e94f04bd
Create Date: 2026-03-09 19:30:18.856993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a43f37c0e5c1'
down_revision: Union[str, Sequence[str], None] = '5207e94f04bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=8), nullable=False),
    sa.Column('white_id', sa.Uuid(), nullable=True),
    sa.Column('black_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'CANCELLED', 'COMPLETED', 'PENDING', name='gamestatus'), nullable=False),
    sa.Column('pub_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['black_id'], ['user_account.id'], name=op.f('fk_game_black_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['white_id'], ['user_account.id'], name=op.f('fk_game_white_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game'))
    )
    op.create_index(op.f('ix_game_game_id'), 'game', ['game_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_game_id'), table_name='game')
    op.drop_table('game')
    op.execute("DROP TYPE gamestatus")

    # ### end Alembic commands ###
