"""create user and preference table

Revision ID: 74819a20a626
Revises: 3243a8d1a03b
Create Date: 2025-12-23 11:48:40.011582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74819a20a626'
down_revision: Union[str, Sequence[str], None] = '3243a8d1a03b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.LargeBinary(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account')),
    sa.UniqueConstraint('email', name=op.f('uq_user_account_email')),
    sa.UniqueConstraint('username', name=op.f('uq_user_account_username'))
    )
    op.create_table('user_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board', sa.Enum('wood', 'blue', 'blue2', 'brown', name='board'), nullable=False),
    sa.Column('pieceset', sa.Enum('base', 'wiki', name='pieceset'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_user_preference_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preference')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_preference_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preference')
    op.drop_table('user_account')
    op.execute("DROP TYPE board")
    op.execute("DROP TYPE pieceset")
    # ### end Alembic commands ###
