"""update challenge

Revision ID: 26151e7d56ee
Revises: 7dec68eb6b68
Create Date: 2026-07-01 02:45:09.548833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26151e7d56ee'
down_revision: Union[str, Sequence[str], None] = '7dec68eb6b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('inital_fen', sa.String(length=100), nullable=False))
    op.add_column('challenge', sa.Column('expire_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP + INTERVAL '7 days'"), nullable=False))
    op.alter_column('challenge', 'time_control',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_challenge_expire_at'), 'challenge', ['expire_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenge_expire_at'), table_name='challenge')
    op.alter_column('challenge', 'time_control',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('challenge', 'expire_at')
    op.drop_column('challenge', 'inital_fen')
    # ### end Alembic commands ###
