"""add server default game

Revision ID: fb3a2b6e58db
Revises: 4d2cefc9f214
Create Date: 2026-07-25 13:56:13.943761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb3a2b6e58db'
down_revision: Union[str, Sequence[str], None] = '4d2cefc9f214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'status',
               existing_type=postgresql.ENUM('created', 'started', 'aborted', 'mate', 'resign', 'stalemate', 'timeout', 'draw', 'nostart', name='gamestatus'),
               server_default='created',
               existing_nullable=False)
    op.alter_column('game', 'meta',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default='{}',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'meta',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('game', 'status',
               existing_type=postgresql.ENUM('created', 'started', 'aborted', 'mate', 'resign', 'stalemate', 'timeout', 'draw', 'nostart', name='gamestatus'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
