"""DDL Game table

Revision ID: 6450d5751f55
Revises: bd4641823473
Create Date: 2026-06-26 00:40:06.278292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6450d5751f55'
down_revision: Union[str, Sequence[str], None] = 'bd4641823473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=8), nullable=False),
    sa.Column('white_id', sa.Uuid(), nullable=True),
    sa.Column('black_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('created', 'started', 'aborted', 'mate', 'resign', 'stalemate', 'timeout', 'draw', 'nostart', name='gamestatus'), nullable=False),
    sa.Column('pub_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('moves', sa.String(), nullable=True),
    sa.Column('clock', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['black_id'], ['user_account.id'], name=op.f('fk_game_black_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['white_id'], ['user_account.id'], name=op.f('fk_game_white_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game'))
    )
    op.create_index(op.f('ix_game_black_id'), 'game', ['black_id'], unique=False)
    op.create_index(op.f('ix_game_game_id'), 'game', ['game_id'], unique=True)
    op.create_index(op.f('ix_game_white_id'), 'game', ['white_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_white_id'), table_name='game')
    op.drop_index(op.f('ix_game_game_id'), table_name='game')
    op.drop_index(op.f('ix_game_black_id'), table_name='game')
    op.drop_table('game')
    op.execute("DROP TYPE gamestatus")

    # ### end Alembic commands ###
