"""add sender id to notification table

Revision ID: bd4641823473
Revises: add235cb1000
Create Date: 2026-05-15 02:28:39.773792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd4641823473'
down_revision: Union[str, Sequence[str], None] = 'add235cb1000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('sender_id', sa.Uuid(), nullable=False))
    op.add_column('notification', sa.Column('receiver_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('fk_notification_user_id_user_account'), 'notification', type_='foreignkey')
    op.create_foreign_key(op.f('fk_notification_sender_id_user_account'), 'notification', 'user_account', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_notification_receiver_id_user_account'), 'notification', 'user_account', ['receiver_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notification', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_notification_receiver_id_user_account'), 'notification', type_='foreignkey')
    op.drop_constraint(op.f('fk_notification_sender_id_user_account'), 'notification', type_='foreignkey')
    op.create_foreign_key(op.f('fk_notification_user_id_user_account'), 'notification', 'user_account', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notification', 'receiver_id')
    op.drop_column('notification', 'sender_id')
    # ### end Alembic commands ###
