"""create notification and friendship table

Revision ID: 3f5e3cc97c6d
Revises: 74819a20a626
Create Date: 2026-02-24 23:04:22.675844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f5e3cc97c6d'
down_revision: Union[str, Sequence[str], None] = '74819a20a626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'blocked', name='friendshipstatus'), nullable=False),
    sa.Column('last_update', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sender_id != receiver_id', name=op.f('ck_friendship_`ck_user_not_friend_with_self`')),
    sa.ForeignKeyConstraint(['receiver_id'], ['user_account.id'], name=op.f('fk_friendship_receiver_id_user_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user_account.id'], name=op.f('fk_friendship_sender_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friendship'))
    )
    op.create_index('ix_unique_friendship', 'friendship', [sa.literal_column("least('sender_id', 'receiver_id')"), sa.literal_column("greatest('sender_id', 'receiver_id')")], unique=True)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('friendship_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friendship_id'], ['friendship.id'], name=op.f('fk_notification_friendship_id_friendship'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_notification_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )

    op.execute("""
        CREATE VIEW user_base AS
        SELECT
            id,
            username,
        FROM user_account;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_index('ix_unique_friendship', table_name='friendship')
    op.drop_table('friendship')
    op.execute("DROP TYPE friendshipstatus")
    op.execute("""
        DROP VIEW IF EXISTS user_base;
    """)
    # ### end Alembic commands ###
