from typing import ClassVar

class UserQueries:
    by_id: ClassVar[str] = ...
    by_username: ClassVar[str] = ...
    by_id_full: ClassVar[str] = ...
    by_username_full: ClassVar[str] = ...
    by_username_profile: ClassVar[str] = ...
    search: ClassVar[str] = ...
