from typing import ClassVar

class UserQueries:
    by_id: ClassVar[str] = ...
    by_username: ClassVar[str] = ...
    by_id_full: ClassVar[str] = ...
    by_username_full: ClassVar[str] = ...
    by_username_profile: ClassVar[str] = ...
    search: ClassVar[str] = ...
    insert: ClassVar[str] = ...
    delete: ClassVar[str] = ...

class NotifQueries:
    get_notifications: ClassVar[str] = ...
    unread_count: ClassVar[str] = ...
    mark_all_read: ClassVar[str] = ...
    delete_all: ClassVar[str] = ...

class WebQueries:
    chess_positions: ClassVar[str] = ...

class SocialQueries:
    create_request: ClassVar[str] = ...
    accept_request: ClassVar[str] = ...
    delete_request: ClassVar[str] = ...
    list_friendship: ClassVar[str] = ...
    delete_friend: ClassVar[str] = ...

class ChallQueries:
    list: ClassVar[str] = ...
    create: ClassVar[str] = ...

class GameQueries:
    create: ClassVar[str] = ...
