from typing import ClassVar

class UserQueries:
    by_id: ClassVar[str] = ...
    by_username: ClassVar[str] = ...
    by_id_full: ClassVar[str] = ...
    by_username_full: ClassVar[str] = ...
    by_username_profile: ClassVar[str] = ...
    search: ClassVar[str] = ...
    insert: ClassVar[str] = ...
    insert_admin: ClassVar[str] = ...
    delete: ClassVar[str] = ...

class PrefQueries:
    insert: ClassVar[str] = ...
