# Generated by Django 5.2.4 on 2025-07-22 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=14, unique=True)),
                ('status', models.CharField(choices=[('CANCELED', 'Cancelled'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending')], max_length=24)),
                ('data', models.JSONField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('black_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_as_black', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_as_white', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'pub_date',
            },
        ),
    ]
