# Generated by Django 5.2.4 on 2025-11-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
